repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: master
    hooks:
      - id: blacken-docs
    additional_dependencies: [black]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
    additional_dependencies: [black]
  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier
    files: "\\.(\
      txt\
      |rst\
      |in\
      |json\
      |yaml|yml\
      )$"
